const DATABASE_NAME = "@gameplay";

const COLLECTION_USERS = `${DATABASE_NAME}:user`;
const COLLECTION_APPOINTMENTS = `${DATABASE_NAME}:appointments`;

export { COLLECTION_APPOINTMENTS, COLLECTION_USERS };
